
services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-16-alpine}
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-elearning_kma}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - backend

  redis:
    image: redis:${REDIS_VERSION:-7-alpine}
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]  # bật AOF để lưu bền
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
#    healthcheck:
#      test: ["CMD", "redis-cli", "PING"]
#      interval: 10s
#      timeout: 3s
#      retries: 5
    networks:
      - backend

  minio:
    image: minio/minio:${MINIO_TAG:-RELEASE.2024-08-17T01-24-54Z}
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-ChangeMe!123}
      MINIO_SERVER_URL: ${MINIO_ENDPOINT:-http://localhost:9000}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
      # (tùy chọn) HTTPS:
      # - ./certs:/root/.minio/certs:ro
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Web console
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  minio_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local
