spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/elearning_kma
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: HikariPool
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
    from: elearningkma@gmail.com
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 300000 # 5 phút
      cache-null-values: false
  ai:
    openai:
      api-key: ${GEMINI_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash
          temperature: 0.7

application:
  jwt:
    signer-key: ${JWT_SECRET_KEY:oQYBztyZyBdLMvdfBLD8RhS3ynD7iwnVnoT8DUJe+XzQh7jignRqFVFLFPbrWaoo}
    valid-duration: 36000 # in seconds
    refreshable-duration: 360000 # in seconds
  mailing:
    front-end:
      verification-code-length: 6
      verification-code-expiration-minutes: 15 # in minutes
      activation-url: http://localhost:4200/activate-account
  minio:
    endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
    access-key: ${MINIO_ROOT_USER}
    secret-key: ${MINIO_ROOT_PASSWORD}
    bucket: resources
    key-prefix: uploads/
    presign-expiry-seconds: 7200 # in seconds
    make-bucket-public: false

server:
  port: 8080
